DROP TABLE IF EXISTS public.airframes;
CREATE TABLE public.airframes (
    icao24 VARCHAR null,
    registration VARCHAR null,
    manufacturericao varchar null,
    manufacturername varchar null,
    model VARCHAR null,
    typecode varchar null,
    serialnumber varchar null,
    linenumber varchar null,
    icaoaircrafttype varchar null,
    operator varchar null,
    operatorcallsign varchar null,
    operatoricao varchar null,
    operatoriata varchar null,
    owner_name varchar null,
    testreg varchar null,
    registered VARCHAR null,
    reguntil varchar null,
    airframe_status varchar null,
    built varchar null,
    firstflightdate varchar null,
    seatconfiguration varchar null,
    engines varchar null,
    modes varchar null,
    adsb varchar null,
    acars varchar null,
    notes varchar null,
    categoryDescription varchar null
)